import { createFileRoute } from "@tanstack/react-router";

export const Route = createFileRoute("/(policy)/tos")({
  component: TermsOfService,
});

function TermsOfService() {
  return (
    <div className="mx-auto max-w-4xl px-4 py-16 sm:px-6 lg:px-8">
      <div className="prose prose-gray dark:prose-invert max-w-none">
        <h1 className="text-4xl font-bold tracking-tight">Terms of Service</h1>
        <p className="text-muted-foreground mt-4 text-lg">
          Last updated:{" "}
          {new Date().toLocaleDateString("en-US", {
            year: "numeric",
            month: "long",
            day: "numeric",
          })}
        </p>

        <div className="mt-12 space-y-8">
          <section>
            <h2 className="text-2xl font-semibold">1. Acceptance of Terms</h2>
            <p className="text-muted-foreground mt-4">
              By accessing or using our AI detection service ("Service"), you agree to be
              bound by these Terms of Service ("Terms"). If you disagree with any part of
              these terms, you may not access the Service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold">2. Description of Service</h2>
            <p className="text-muted-foreground mt-4">
              Our Service provides AI content detection and analysis tools that help
              identify whether text content was likely generated by artificial
              intelligence or written by humans. The Service uses multiple detection
              algorithms and provides probability scores based on various indicators.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold">3. User Accounts</h2>
            <p className="text-muted-foreground mt-4">
              To access certain features of the Service, you may be required to create an
              account. You are responsible for:
            </p>
            <ul className="text-muted-foreground mt-2 list-inside list-disc space-y-2">
              <li>Maintaining the confidentiality of your account credentials</li>
              <li>All activities that occur under your account</li>
              <li>Notifying us immediately of any unauthorized use</li>
              <li>Providing accurate and complete information during registration</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold">4. Acceptable Use Policy</h2>
            <p className="text-muted-foreground mt-4">
              You agree not to use the Service to:
            </p>
            <ul className="text-muted-foreground mt-2 list-inside list-disc space-y-2">
              <li>Violate any applicable laws or regulations</li>
              <li>Infringe upon intellectual property rights of others</li>
              <li>Submit content that is defamatory, offensive, or harmful</li>
              <li>Attempt to circumvent or manipulate the detection algorithms</li>
              <li>Use automated systems or bots without permission</li>
              <li>Reverse engineer or attempt to extract the source code</li>
              <li>Overload or disrupt the Service infrastructure</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold">5. Content and Privacy</h2>
            <p className="text-muted-foreground mt-4">
              <strong>Your Content:</strong> You retain all rights to the content you
              submit for analysis. By using the Service, you grant us a limited license to
              process and analyze your content solely for the purpose of providing the
              Service.
            </p>
            <p className="text-muted-foreground mt-4">
              <strong>Data Processing:</strong> We process submitted text temporarily and
              do not permanently store analyzed content unless you explicitly save it to
              your account. We implement industry-standard security measures to protect
              your data.
            </p>
            <p className="text-muted-foreground mt-4">
              <strong>Confidentiality:</strong> We treat all submitted content as
              confidential and do not share it with third parties, except as required by
              law or with your explicit consent.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold">6. Accuracy and Limitations</h2>
            <p className="text-muted-foreground mt-4">
              <strong>No Guarantee of Accuracy:</strong> While we strive for accuracy, AI
              detection is probabilistic and not 100% reliable. Results should be
              considered as indicators rather than definitive proof of AI or human
              authorship.
            </p>
            <p className="text-muted-foreground mt-4">
              <strong>Educational Purpose:</strong> The Service is intended for
              educational, research, and informational purposes. Critical decisions should
              not be based solely on our detection results.
            </p>
            <p className="text-muted-foreground mt-4">
              <strong>False Positives/Negatives:</strong> The Service may occasionally
              produce false positives (human text identified as AI) or false negatives (AI
              text identified as human). Users should use their judgment and consider
              multiple factors.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold">7. Intellectual Property</h2>
            <p className="text-muted-foreground mt-4">
              The Service, including its original content, features, and functionality, is
              owned by us and is protected by international copyright, trademark, patent,
              trade secret, and other intellectual property laws.
            </p>
            <p className="text-muted-foreground mt-4">
              Our trademarks and trade dress may not be used in connection with any
              product or service without our prior written consent.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold">8. Pricing and Payment</h2>
            <p className="text-muted-foreground mt-4">
              <strong>Free Tier:</strong> We offer limited free access to the Service with
              usage restrictions.
            </p>
            <p className="text-muted-foreground mt-4">
              <strong>Premium Services:</strong> Additional features and higher usage
              limits are available through paid subscriptions. Prices are subject to
              change with 30 days notice.
            </p>
            <p className="text-muted-foreground mt-4">
              <strong>Refunds:</strong> Subscription fees are generally non-refundable
              except as required by law or as explicitly stated in our refund policy.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold">
              9. Disclaimers and Limitation of Liability
            </h2>
            <p className="text-muted-foreground mt-4">
              THE SERVICE IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND, EITHER
              EXPRESS OR IMPLIED. WE DISCLAIM ALL WARRANTIES, INCLUDING BUT NOT LIMITED TO
              MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
            </p>
            <p className="text-muted-foreground mt-4">
              IN NO EVENT SHALL WE BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL,
              CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING OUT OF OR RELATED TO YOUR USE OF
              THE SERVICE, WHETHER BASED IN CONTRACT, TORT, STRICT LIABILITY, OR
              OTHERWISE.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold">10. Indemnification</h2>
            <p className="text-muted-foreground mt-4">
              You agree to indemnify, defend, and hold harmless our company, its officers,
              directors, employees, and agents from any claims, liabilities, damages,
              losses, and expenses arising from your use of the Service or violation of
              these Terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold">11. Termination</h2>
            <p className="text-muted-foreground mt-4">
              We reserve the right to terminate or suspend your account and access to the
              Service at our sole discretion, without notice, for conduct that we believe
              violates these Terms or is harmful to other users, us, or third parties.
            </p>
            <p className="text-muted-foreground mt-4">
              You may terminate your account at any time by contacting our support team.
              Upon termination, your right to use the Service will immediately cease.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold">12. Governing Law</h2>
            <p className="text-muted-foreground mt-4">
              These Terms shall be governed by and construed in accordance with the laws
              of the United States, without regard to its conflict of law provisions. Any
              disputes arising under these Terms shall be subject to the exclusive
              jurisdiction of the courts in the United States.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold">13. Changes to Terms</h2>
            <p className="text-muted-foreground mt-4">
              We reserve the right to modify these Terms at any time. We will notify users
              of any material changes by posting the new Terms on this page and updating
              the "Last updated" date. Your continued use of the Service after changes
              constitutes acceptance of the modified Terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold">14. Contact Information</h2>
            <p className="text-muted-foreground mt-4">
              If you have any questions about these Terms of Service, please contact us
              at:
            </p>
            <div className="text-muted-foreground mt-4 space-y-2">
              <p>Email: support@overgpt.com</p>
            </div>
          </section>

          <section className="border-t pt-8">
            <h2 className="text-2xl font-semibold">15. Miscellaneous</h2>
            <p className="text-muted-foreground mt-4">
              <strong>Entire Agreement:</strong> These Terms constitute the entire
              agreement between you and us regarding the Service.
            </p>
            <p className="text-muted-foreground mt-4">
              <strong>Severability:</strong> If any provision of these Terms is found to
              be unenforceable, the remaining provisions will continue in effect.
            </p>
            <p className="text-muted-foreground mt-4">
              <strong>Waiver:</strong> No waiver of any term of these Terms shall be
              deemed a further or continuing waiver of such term or any other term.
            </p>
            <p className="text-muted-foreground mt-4">
              <strong>Assignment:</strong> You may not assign or transfer your rights
              under these Terms without our prior written consent.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
